#!/bin/bash

BAT="$(which battery 2>/dev/null)"

if [[ -z "$BAT" ]]; then
    BAT="$(dirname $(readlink -f "$0"))/battery"
fi

if [[ ! -x "$BAT" ]]; then
    wall <<<"battery-guard could not find battery script!"
fi

TOTAL=$($BAT --total)
if [[ $TOTAL -lt 4 ]]; then
    AC_PLUGGED="$(cat /sys/class/power_supply/AC/online 2>/dev/null)"
    [[ "$AC_PLUGGED" = "1" ]] && exit 0
    wall <<<"battery-guard: suspending due to very low power!"
    sudo pm-suspend
fi
