#!/bin/bash

SHOWTOTAL=$([[ "${1:-}" == "--total" ]] && echo 1 || echo 2)
TOTAL=0
DELIM=" ~ "

for STATDIR in /sys/class/power_supply/*;
do
	[ $(cat ${STATDIR}/type) == "Battery" ] || continue;

    # before sourcing new values, ensure we forgot previous battery ones
    unset POWER_SUPPLY_NAME POWER_SUPPLY_MODEL_NAME POWER_SUPPLY_TECHNOLOGY POWER_SUPPLY_TYPE
    unset POWER_SUPPLY_CHARGE_FULL POWER_SUPPLY_CHARGE_NOW
    unset POWER_SUPPLY_ENERGY_FULL POWER_SUPPLY_ENERGY_NOW

	#. ${STATDIR}/uevent
	### bohuzel uevent obsahuje hodnoty neobalene v uvozovkach
	### a lomitka v SERIAL_NUMBER narusi "source(.)"
	### proto musime ten radek vynechat
	for EXP in $(grep -v "SERIAL_NUMBER" ${STATDIR}/uevent);
	do
		eval $EXP
	done


	[ "${POWER_SUPPLY_PRESENT}" == "1" ] || continue;

    [[ -z "$POWER_SUPPLY_CHARGE_NOW" ]] \
        && POWER_SUPPLY_CHARGE_NOW="$POWER_SUPPLY_ENERGY_NOW"
    [[ -z "$POWER_SUPPLY_CHARGE_FULL" ]] \
        && POWER_SUPPLY_CHARGE_FULL="$POWER_SUPPLY_ENERGY_FULL"

	PERC=$(echo "scale=2; ${POWER_SUPPLY_CHARGE_NOW} / (${POWER_SUPPLY_CHARGE_FULL}/100)" | bc)
    TOTAL=$(echo "scale=2; ${TOTAL} + ${PERC}" | bc)

    [[ "$SHOWTOTAL" == "1" ]] && continue;

	echo -n "${POWER_SUPPLY_NAME}"
	echo -n "${DELIM}"
	echo -n "${POWER_SUPPLY_MODEL_NAME} ${POWER_SUPPLY_TECHNOLOGY} ${POWER_SUPPLY_TYPE}"
	echo -n "${DELIM}"
	echo -n "${PERC}%"
	echo -n "${DELIM}"
	echo -n "${POWER_SUPPLY_STATUS}"
	echo ""

done

if [[ "$SHOWTOTAL" == "1" ]]; then
    echo "scale=0; ${TOTAL} / 1" | bc
fi

#CURR=`grep "remaining" /proc/acpi/battery/C1BE/state | sed "s/^[^0-9]*\([0-9]*\).*$/\1/"`
#MAX=`grep "last" /proc/acpi/battery/C1BE/info | sed "s/^[^0-9]*\([0-9]*\).*$/\1/"`
#CHARGE=`grep "charging" /proc/acpi/battery/C1BE/state | sed "s/^.*:\W*//"`
#echo ${CURR}"/"${MAX}" - "${CHARGE}

