#!/bin/dash

#use #!/bin/bash if you dont have Dash

#though in my case its just few (~10) ms ...
#... in % its 13-17 gain - why not :)
#next version i may try in go - promise :)

OURDIR="$HOME/.cache/dmenu_hist"
if [ ! -d "$OURDIR" ]; then
    if [ -f "$OURDIR" ]; then
        mv "$OURDIR" "$OURDIR-bup"
        mkdir -p "$OURDIR"
        mv "$OURDIR-bup" "$OURDIR/history"
    else
        mkdir -p "$OURDIR"
    fi
fi
HIST="$OURDIR/history"
CACHE="$OURDIR/cache"


##### BASIC help/args section #####

if [ "x$1" = "x--help" ]; then
    cat <<EOF

$(basename $0) [--edit|--noop] [dmenu-args...]

    Launch dmenu with choices built from all executables
    from folders in PATH, but prefer those already picked before,
    with last choice provided as first option.

    Our args (has to be specified first):
    --edit   open history file [$HIST] in editor
    --noop   just prepare everything for launching dmenu,
             but do not launch it (good for timing perf etc)

    any other following/remaining args will be passed
    directly to dmenu(1).
EOF
    exit
fi

if [ "x$1" = "x--edit" ]; then
    if [ "x" = "x$EDITOR" ]; then
        echo "You did not set $$EDITOR .. using vi"
        EDITOR=/usr/bin/vi
    fi
    exec $EDITOR $HIST
fi

DMENU_CMD=dmenu
if [ "x$1" = "x--noop" ]; then
    DMENU_CMD=echo
    shift
fi


##### FIND EXECUTABLES IN PATH #####

## get the modification time of latest changed
## directory in path
LASTCHANGE="$(
(IFS=:;
    for p in $PATH;
        do stat --format "%Z" $p;
    done;
) | sort -r| head -n1)"

## if we have cache and it is older, remove it
[ -f "$CACHE" -a $LASTCHANGE -gt $(stat --format "%Z" $CACHE) ] && rm $CACHE

if [ ! -f "$CACHE" ]; then
    # if we dont have cache, lets create one
    CACHE_TMP="$(mktemp --suffix qdmenu)"
    trap "rm $CACHE_TMP" EXIT
    ( IFS=:;
    for p in $PATH; do
        find -L $p -maxdepth 1 -type f -executable -printf "%f\n" >> $CACHE_TMP 2> /dev/null ;
    done;
    )
    sort -u $CACHE_TMP > $CACHE
fi


##### CALL DMENU TO GET USER CHOICE #####

touch "$HIST"
CHOICE="$( (tac $HIST; grep -v -f $HIST $CACHE) | $DMENU_CMD "$@")"
[ "x" = "x$CHOICE" ] && exit


##### SAVE USER CHOICE IN HISTORY #####

sed -i "/^$CHOICE$/d" $HIST
echo $CHOICE >> $HIST


##### EXECUTE USER CHOICE #####
$CHOICE &
