#!/bin/bash
set -ex


# TODO:
#
# 1) Legend for gpuXYZ variables - how to map to basic nvidia-smi output
# >>  # gpu   pwr  temp    sm   mem   enc   dec  mclk  pclk    fb  bar1 rxpci txpci
# >>  # Idx     W     C     %     %     %     %   MHz   MHz    MB    MB  MB/s  MB/s
# >>      0    64    64    53    28     0     0  3304  1417   612     5    62   107
# >>  Sun Dec  3 22:14:51 2017
# >>  +-----------------------------------------------------------------------------+
# >>  | NVIDIA-SMI 375.82                 Driver Version: 375.82                    |
# >>  |-------------------------------+----------------------+----------------------+
# >>  | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
# >>  | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
# >>  |===============================+======================+======================|
# >>  |   0  GeForce GTX 950     Off  | 0000:01:00.0      On |                  N/A |
# >>  | 31%   64C    P0    64W /  99W |    612MiB /  1996MiB |     53%      Default |
# >>  +-------------------------------+----------------------+----------------------+
# ... seems 'sm' is the GPU-Util ...
# ... record/plot pwr,temp,sm,memp/fb?/, [rt]xpci?
#
# 2) http://codeblog.dotsandbrackets.com/quick-intro-to-rrdtool/
#    - create empty rrd's
#    - add data in every iteration
#    - instead of 'echo recalculating' generate graphs


# for debug
KEEP=1
###########

MONPIDS=""

[[ -n "$KEEP" ]] && { T="/tmp/gamemon"; rm -rf "$T"; mkdir -p "$T"; }
T="${T:-$(mktemp -d --suffix -gamemon)}"
[[ -n "$T" ]] && trap '[[ -n "$MONPIDS" ]] && kill $MONPIDS; [[ -z "$KEEP" ]] && rm -rf "${T}"' EXIT
trap "echo recalculating" INT

#nvidia-smi dmon -s pucmt -o T -f "$T/gpu.log" &
#GPUPID=$!
#MONPIDS="$MONPIDS $GPUPID"

while true; do
    t_start=$(date "+%s.%N")

    memFree="$(sed -rn 's/(MemAva).* +([0-9]+) .*/\2/p' /proc/meminfo)"
    #mem="$(for X in $mem; do echo "scale=0; $X / 1024" | bc; done)"

    # cpu = '<float:user> <float:sys> <float:idle>'
    cpu="$(top -b -n1 | sed -nr 's/^%Cpu\(s\): +([0-9.]+) us, +([0-9.]+) sy, .* ([0-9.]+) id, .*/\1 \2\ \3/p')"
    read cpuUsr cpuSys cpuIdl <<<"$cpu"


    gpu=$(nvidia-smi dmon -c 1 -s pucmt | tail -n1)
    read gpuIdx gpuPwr gpuTemp gpuSm gpuMemP gpuEnc gpuDec gpuMClk gpuPClk gpuFB gpuBar1 gpuRxPci gpuTxPci <<<"$gpu"

    echo "$memFree"
    echo "$cpuUsr"
    echo "$cpuSys"
    echo "$cpuIdl"

    echo "$gpu"
    echo "$gpuTemp"
    echo "$gpuMemP"

    #echo "$mem" >> "$T/mem.log"
    #echo "$cpu" >> "$T/cpu.log"

    t_sleep=$(bc <<<"1 - ( $(date "+%s.%N") - $t_start )")
    sleep $t_sleep;
done
