#!/usr/bin/python

import re
import sys

pattern = re.compile('[0-9a-f]+  ([0-9a-fA-F ]+) \|.*')

if len(sys.argv) < 3:
    print("Usage: hexdump-restore <hexdump-output-file>"
          " <destination-of-restoration>")
    sys.exit(1)

total = 0
with open(sys.argv[1], 'r') as source:
    with open(sys.argv[2], 'w') as dest:
        for line in source:
            m = pattern.match(line)
            if not m:
                print('no match for: %s' % line)
            else:
                nums = filter(None,
                              [n.strip()
                               for n
                               in m.group(1).split(' ')])
                data = bytearray.fromhex(''.join(nums))
                total += len(data)
                dest.write(data)
print(' %d bytes written' % total)
