#!/usr/bin/env python

import fileinput
import yaml
import json

src = ''.join(fileinput.input())
obj = json.loads(src)
print yaml.safe_dump(obj,
                     indent=2,
                     default_flow_style=False,
                     explicit_start=True,
                     allow_unicode=True,
                     encoding='utf-8')
