#!/bin/bash

echo ""

LABEL="${LABEL:-${USER}-${!#}}"  # last arg is my ident of the run

export CONFIG_BASE="${CONFIG_BASE:-${KHALDIR:-"/all/src/khaleesi"}"-settings"}"
DEST_FILE="/all/src/kset/${LABEL}.yaml"

echo "Config dir: $CONFIG_BASE"
echo "Tgt file: $DEST_FILE"

if [[ "$@" != "help" ]]; then
    #echo "--- before ---"
    #echo "$ARGS"
    #echo "--------------"

    ARGS="${@:1:$(($# - 1))}"  # strip last
    ARGS="$(sed -r 's/ ?--provisioner-site[^ ]+//g' <<< "$ARGS" )"
    ARGS="$(sed -r 's/ ?--config-dir[^ ]+//g' <<< "$ARGS" )"
    ARGS="$(sed -r 's/ ?--extra-vars provisioner.key_file=[^ ]*//g' <<< "$ARGS" )"

    #echo "--- stripped ---"
    #echo "$ARGS"
    #echo "----------------"

    ARGS="--config-dir=./settings $ARGS"
    ARGS="$ARGS --provisioner-site=qeos"
    ARGS="$ARGS --provisioner-site-user=psedlak"
    ARGS="$ARGS --extra-vars provisioner.key_file=${HOME}/.ssh/rhos-jenkins"
    ARGS="$ARGS --extra-vars tmp.node_prefix=${LABEL}-"
    ARGS="$ARGS ${DEST_FILE}"
else
    ARGS="$@"
    ARGS="--config-dir=./settings ${ARGS}"
fi

set -x
cd $CONFIG_BASE
$HOME/.local/bin/ksgen ${ARGS}

#"${@:1:$(($# - 1))}" \
 #   "/all/src/khaleesi/psedlak-${!#}.yaml"
    #--provisioner-site=qeos \
    #--provisioner-site-user=rhos-dev \
    #--extra-vars "provisioner.key_file=rhos-jenkins" \
