#!/bin/bash

N=/dev/null

checkproc() {
    # TODO: rewrite this too
    ps -ef 2>&1 | grep $1 2>&1 | grep -v grep
}

if checkproc qmmp &> $N; then
	echo "qmmp - nepodporovano";
elif checkproc amarok &> $N; then
    if dcop amarok player isPlaying &> $N; then
			dcop amarok player nowPlaying
    fi
elif checkproc mpd &> $N; then
    mpc current
else
    FILE=$(find ~/ -maxdepth 1 -type f -name .nowplaying -mmin -60 -print)
    [[ -f "$FILE" ]] && cat "$FILE" || echo
    # empty echo - nothing playing but we provide line
fi


