#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib $FindBin::Bin;
use Net::Ping::External qw(ping);
use POSIX qw(strftime);
use X::Osd;
# --------------------------

my $server = "nix.cz";
my $interval = 3;
my $osd_interval = 0;
my $color_on = "Gray";
my $color_off = "Red";

# --------------------------
# --------------------------
# --------------------------

my $osd = X::Osd->new(1);
$osd->set_font("-*-terminal-*-r-*-*-*-140-*-*-*-*-*-*");
$osd->set_timeout($osd_interval) if $osd_interval > 0;
$osd->set_pos(XOSD_top);
$osd->set_align(XOSD_left);

sub my_ping {
	my $host = shift;
	my $count = shift;
	my $command = "ping -n -c $count $host";
	my $devnull = "/dev/null";
	$command .= " 1>$devnull 2>$devnull";
	my $exit_status = system($command) >> 8;
	return 1 if $exit_status == 0;
	return 0;
}
sub pingtest {
	my $host = shift;
	return my_ping($host, 2);
	# return Net::Ping::External::ping(host => $host, count => 2);
}

sub display_msg {
	my $online = shift;
	my $ms;
	if($online){
		$ms = "Online";
		$osd->set_colour($color_on);
	} else {
		$ms = "OFFLINE";
		$osd->set_colour($color_off);
	}
	print strftime("%Y%m%d-%H%M%S",localtime());
	print ": ", $ms, "\n";
	$osd->string(0, $ms);
}

my $last = -1;

my $ip = join(".", unpack("C4", (gethostbyname($server))[4]));

print "Pinging ", $ip, " [", $server, "] each $interval sec.\n";
while(1) {
	my $res = pingtest($ip);
	if($res != $last) {
		$last = $res;
		display_msg($res);
	}
	sleep($interval);
}

