#!/bin/bash

yum=$(command -v dnf yum | head -n1)
sudo $yum install -y \
    vim-enhanced \
    screen \
    strace \
    htop

if [[ ! "$PATH" =~ "$HOME/scripts" ]]; then
	echo 'export PATH="$PATH:$HOME/scripts"' >> $HOME/.bashrc
fi
