#!/bin/bash
UNLOCK=false
if [[ "$1" = "-u" ]]; then UNLOCK=true; shift; fi

if [[ ! -z "$DISPLAY" ]] && ! $UNLOCK && [[ "$1" != "forked" ]]; then
    $0 forked "$@" &
    exit 0
fi


echo "$(date): qslock: DISP=$DISPLAY UNLOCK=$UNLOCK" >> ~/qslock.log
tail -n1 ~/qslock.log > ~/osd-notes

if [[ -z "$DISPLAY" ]]; then
    if $UNLOCK; then pkill vlock; exit; fi
    if ! which vlock > /dev/null; then
        echo "Unable to find vlock!" >&2
        exit 1
    fi
    clear
    echo " Now You will be upgraded, please stand-by ..."
    echo ""
    echo " Error: You are incompatible with Cyberman upgrade."
    echo " DELETE! DELETE! DELETE!"
    echo ""
    vlock --all
else
    if $UNLOCK; then
        pkill i3lock;
        xset -display :0.0 dpms force on;
        exit;
    fi
    if ! which i3lock > /dev/null; then
        echo "Unable to find i3lock!" >&2
        exit 1
    fi
    qdbus-qt5 org.kde.konversation /irc org.kde.konversation.setAway 'AFK' &> /dev/null
    i3lock \
        --nofork \
        -p default \
        \ #-c ff2222 \
        -i /all/pictures/wall/danger/dark_cyber___by_steelgohst_by_steelgohst-d5hnyrs.png \
        -d #dpms
    qdbus-qt5 org.kde.konversation /irc org.kde.konversation.setBack &> /dev/null
fi
