#!/bin/bash

INOTIFY=$(which inotifywait)
if [ -z "$INOTIFY" -o ! -x "$INOTIFY" ];
then
  echo "This script requires inotifywait:"
  echo "- please install package inotify-tools (or equiv for you distro)."
  exit 2
fi

FILE="$1"
shift

if [ ! -f "$FILE" ];
then
  echo "first argument has to be path to monitored file"
  exit 1
fi


SUMMER=$(which sha1sum)
OLDSUM=$($SUMMER $FILE)
NEWSUM=

NOTIFYOPTS="-e DELETE_SELF"

while inotifywait $NOTIFYOPTS $FILE > /dev/null 2>&1;
do
  echo ""
  echo "-------------[  running on change  ]-----------"
  NEWSUM=$($SUMMER $FILE)
  if [ "$OLDSUM" != "$NEWSUM" ];
  then
    OLDSUM="$NEWSUM"
    eval "$@"
  fi
done

echo "finished"
