#!/bin/bash

SESSIONS=$(screen -list|grep -P "\t[0-9]")
if [[ "$(wc -l <<<"$SESSIONS")" != "1" ]]; then
    echo "Seems there is no just-one screen session:"
    echo "$SESSIONS"
    exit 1
fi

termapp="xterm"
which urxvt &> /dev/null && termapp=urxvt
which urxvtc &> /dev/null && ps -fu psedlak -U psedlak|grep urxvtd|grep -qv grep && termapp=urxvtc

screen -D
for WIN in $(screen -Q windows | sed "s/  /\n/g" | sed -nr "s/^([0-9]+).*/\1/p"); do
    $termapp -e screen -x -p $WIN
done
