#!/bin/bash

# url = http://slovnik.seznam.cz/?lang=cz_en&q=slovo

SOUBOR=`mktemp -p /tmp/`
FIRST=$1
WORD=$2
VERBOSE=false

PROG=`basename $0`
if [ "$PROG" != "trans" ];
then
	FIRST=$PROG
	WORD=$1
    if [[ "$2" == "-v" || "$2" == "--verbose" ]]
    then
        VERBOSE=true
    fi
fi

case $FIRST in
	"encz" )
		TRANSLANG="en-cz";;
	"czen" )
		TRANSLANG="cz-en";;
	* )
		echo "............ chyba argumentu"
		echo
		echo "zadejte dva argumenty"
		echo " - prvni: jazyk prekladu {encz|czen}"
		echo " - druhy: hledane slovo"
		rm $SOUBOR
		exit 1;;
esac

echo -ne "\rdownloading ..."

URL="http://slovnik.seznam.cz/"$TRANSLANG"/word/?q="$WORD

links -no-connect -dump $URL > $SOUBOR
echo -ne "\rparsing 1/2 ..."

TOPLINE=`cat $SOUBOR | grep -B 999 -n "Prekladovy slovnik" | wc -l `
TOPLINE=$(($TOPLINE + 2))
echo -ne "\rparsing 2/3 ..."
if $VERBOSE
then
    STOPLINE=`cat $SOUBOR | grep -B 999 -n "Tiraz" | wc -l `
else
    STOPLINE=`cat $SOUBOR | grep -B 999 -n "Pokrocila gramatika" | wc -l `
fi
STOPLINE=$(($STOPLINE - 3))
ENDLINE=`echo "$STOPLINE - $TOPLINE + 1"|bc `
echo -e "\r                               "


head -n $STOPLINE $SOUBOR | tail -n $ENDLINE | grep -v "Prehrat zvuk"|grep -v "Pridat do mych slov"

rm $SOUBOR

