#!/bin/bash

. "$(dirname $(readlink -f $0))/colorize"

EXIT_OK=0
EXIT_NO_TMP=3
EXIT_CD_TMP=4
EXIT_MENC=5
EXIT_MENC2=6

PARTIAL=""
INPUTS=()
OUTPUTS=()

quit() {
    set +x
    if [[ ! -z "$TMP" && -d "$TMP" ]]; then
        debug "Deleting temp folder $TMP"
        rm -rf $TMP
    else
        warn "No temp folder? $TMP"
    fi
    if [[ ! -z "$PARTIAL" && -f "$PARTIAL" ]]; then
        warn "Removing partial file $PARTIAL"
        rm "$PARTIAL"
    else
        debug "No partial file left behind."
    fi
    CODE=${1:-0}
    [[ ! -z "$2" && $CODE != 0 ]] && error "$2"
    [[ ! -z "$2" && $CODE = 0 ]] && info "$2"
    exit $CODE
}

TMP="$(mktemp -d --tmpdir vid2stb.XXXXXXX)"
[[ -d "$TMP" ]] || exit $EXIT_NO_TMP
trap quit INT TERM

for F in "$@"; do
    INPUTS=("${INPUTS[@]}" "$(readlink -f "$F")")
done


cd "$TMP" || quit $EXIT_CD_TMP "Unable to cd to tmp dir $TMP"

for INPUT in "${INPUTS[@]}"; do
    info "Converting $INPUT"
    OUTPUT="${INPUT%.*}-conv.avi"
    if [[ -f "$OUTPUT" ]]; then
        NUM=1
        while [[ -f "$OUTPUT" ]]; do
            OUTPUT="${INPUT%.*}-conv-${NUM}.avi"
            NUM="$(( $NUM + 1 ))"
        done
        warn "Output file already exists! Going to save as $OUTPUT instead."
    fi
    info "Using output file $OUTPUT."

    USE_LAVC=${LAVC:-0}
    USE_THREADS=${THREADS:-0}

    THREADS=""
    [[ $USE_THREADS != 0 ]] && THREADS=":threads=${USE_THREADS}"
    PASSFILE="$TMP/$(basename "${INPUT}")_pass.log"
    PARTIAL="$OUTPUT"
    OPTS=""
    #OPTS="${OPTS} -vf scale=320:240"
    if [[ $USE_LAVC = 1 ]]; then
        #OPTS="$OPTS -ofps 30000/1001"
        OPTS="$OPTS -oac lavc"
        OPTS="$OPTS -ovc lavc"
        OPTS="$OPTS -lavfopts format=avi"
        OPTS="$OPTS -lavcopts"
        OPTS="${OPTS} acodec=ac3:vcodec=mpeg2video"
        OPTS="${OPTS}${THREADS}"
        OPTS_PASS1="${OPTS}:vpass=1"
        OPTS_PASS2="${OPTS}:mbd=2:trell:vpass=2"
    else
        OPTS="$OPTS -oac lavc -lavcopts acodec=ac3:abitrate=128"
        OPTS="$OPTS -ovc xvid" 
        OPTS="$OPTS -xvidencopts bitrate=600"
        OPTS="${OPTS}${THREADS}"
        OPTS_PASS1="${OPTS}:turbo:pass=1"
        OPTS_PASS2="${OPTS}:trellis:pass=2"
    fi
    set -x
    mencoder "${INPUT}" -o /dev/null   -passlogfile "${PASSFILE}" ${OPTS_PASS1} || quit $EXIT_MENC "First mencoder pass failed"
    mencoder "${INPUT}" -o "${OUTPUT}" -passlogfile "${PASSFILE}" ${OPTS_PASS2} || quit $EXIT_MENC2 "Second mencoder pass failed"
    set +x
    PARTIAL=""
    OUTPUTS=("${OUTPUTS[@]}" "$OUTPUT")
done

info "Generated files:"
for OUT in "${OUTPUTS[@]}"; do
    notice "- $OUT"
done

quit $EXIT_OK "Done"
