#!/bin/bash 

if [ -z "${GAMEDIR}" ] || [ -z "${LOG}" ] || [ -z "${EXE}" ];
then
	echo
	echo "Je potreba zadat shell promenne GAMEDIR, LOG, EXE"
	echo "napr.: "
	echo
	echo "$ GAMEDIR=/games/cs LOG=/games/cs/log EXE=cstrike.exe winegame"
	exit 1
fi

export GAMEDIR LOG EXE

# new entry in log
touch ${LOG}
echo >> ${LOG}
echo "!!! -----------    "`date "+%y%m%d_%H_%M_%S"` >> ${LOG}

cd $GAMEDIR
wine $EXE >> ${LOG} 2>&1

#X :3 -ac -terminate &   # Launch on a new X session on display 3
#cd "${GAMEDIR}"        # Goto game dir
#sleep 2
#DISPLAY=:3 `which wine` ${EXE} >> ${LOG} 2>&1 # Launches

