#!/bin/bash

OSD_POS="-p top -A right -i 20"
OSD_FONT="-misc-fixed-medium-r-*-*-*-70-*-*-*-*-*-*"
OSD_COLOR="-c yellow -O 1 -u black"
CPU_SENSOR="temp1" #Core

echo "starting"

if [ "$1" = "test" ];
then
    CMD=cat
    SLEEP=1
else
    CMD="osd_cat -l 1 $OSD_COLOR $OSD_POS -f $OSD_FONT"
    SLEEP=2
fi

if which mpstat &> /dev/null;
then
    HAS_MPSTAT=true
else
    HAS_MPSTAT=false
    echo "mpstat is missing, cpu usage will be probably out of actual values"
    echo "please install sysstat package (fedora/debian...)"
    echo ""
fi

if which nowplaying &> /dev/null;
then
    HAS_NOWPLAY=true
else
    HAS_NOWPLAY=false
    echo "nowplaying script is missing, no current song info will be displayed"
    echo "you can grab it from the same repo as this (xosd-sysmon)"
    echo ""
fi

if which sensors &> /dev/null;
then
    HAS_SENSORS=true
else
    HAS_SENSORS=false
    echo "sensors command is missing, please install (and set-up) lm-sensors"
    echo "to be able to watch cpu temperature"
    echo ""
fi


while true;
do
    if $HAS_MPSTAT
    then
        CPU_IDLE=$(mpstat -u 1 1|grep Average|sed 's/.*\W\([0-9]*\)\.\([0-9]\+\)$/\1/')
    else
        CPU_IDLE=$(top -n 1|grep Cpu|awk '{ print $5 }'|sed "s/\(.*\)\..*/\1/")
    fi
    CPU_USAGE=$(( 100 - $CPU_IDLE ))
    CPU_TEMP=""
    if $HAS_SENSORS
    then
        CPU_TEMP=$(sensors|grep "${CPU_SENSOR:-Core}"|sed "s/.* \(+[0-9\.]\+.\{2\}\) .*/\\1/")
    fi

    MEM_FREE=$(free -m|grep Mem|awk '{print $4 + $7}')
    SWAP_USED=$(free -m|grep Swap|awk '{print $3}')

    NOWPLAYING=""
    if $HAS_NOWPLAY
    then
        NOWPLAYING=$(nowplaying)
    fi

    #DATE=$(date)
    MSG="$NOWPLAYING | CPU $CPU_USAGE% $CPU_TEMP | MEM ${MEM_FREE} free ${SWAP_USED} swapped"

    #echo $MSG | osd_cat -d 1 $OSD_COLOR $OSD_POS -f $OSD_FONT
    #echo "next round?"
    echo "$MSG"
    sleep $SLEEP
done | $CMD

echo "exiting"
